version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: pg-db
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ./templates:/templates